### ISSUE TITLE
Keyword-based prefix parsing errors

### ISSUE THREAD

**Issue by tbabej** [GothenburgBitFactory/taskwarrior#2353]
Certain TW keywords can trigger parsing errors. This umbrella issue serves to group the issues together (and deduplicate the issue list), as these are caused by the same/similar underlying mechanisms in the parser:

* [x] [TW-1805] project:ide is not allowed #1826 (fixed, along with duplicates #2351,  #2069)
* [x] [TW-1786] Project name can't start with 'project' #1809 (fixed)
* [x] project:parents is disallowed #2129 (fixed)
* [x] Adding task from taskwiki fails #2131 (fixed)
* [ ] UDA string fields can't start with certain keywords #2257 
* [ ] [TW-1895] Cannot create task with explicit description 'start ....' #1908 

The two outstanding issues are likely the same issue (which is actually caused by any attribute name in `description:'<attribute> something'` expression).

**Comment by tbabej** [comment]
Closing umbrella issues to help clean up the issue list. Parsing-related issues can be found in the "Parsing issues" project.
